[package]
name = "learning-opengl"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
c_str_macro = "1.0.3"
gl = "0.14.0"
glfw = "0.53.0"
